development:
  adapter: postgresql
  encoding: utf8
  database: DevcampPortfolio_development
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: utf8
  database: DevcampPortfolio_test
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: DevcampPortfolio_production
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: password
