development:
  adapter: postgresql
  encoding: utf8
  database: DevcampPortfolio_development
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: watchtower1

test:
  adapter: postgresql
  encoding: utf8
  database: DevcampPortfolio_test
  pool: 5
  timeout: 5000
  username: postgres
  password: watchtower1

production:
  adapter: postgresql
  encoding: utf8
  database: DevcampPortfolio_production
  pool: 5
  timeout: 5000
  username: postgres
  password: watchtower1